[package]
name = "t_renderer"
version = "0.2.0"
authors = ["acados authors"]
edition = "2018"

[dependencies]
tera = "1.19"
serde_json = "1.0"
clap = { version = "4.4.11", features = ["derive"] }

[profile.release]
opt-level = 'z'
