name: Releases

on: push

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            architecture: linux-amd64
          - runs-on: macos-13
            architecture: osx-amd64
          - runs-on: windows-latest
            architecture: windows-amd64
          - runs-on: ubuntu-24.04-arm
            architecture: linux-arm64
          - runs-on: windows-11-arm
            architecture: windows-arm64
          - runs-on: macos-latest
            architecture: osx-arm64

    name: Build on ${{ matrix.architecture }}

    steps:
      - name: Setup | Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --verbose --release;

      - name: Rename & move built t_renderer
        shell: bash
        run: |
          EXT=""
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            EXT=".exe"
          fi
          mv target/release/t_renderer$EXT t_renderer-${{ matrix.architecture }}

      - name: Upload t_renderer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: t_renderer-${{ matrix.architecture }}
          path: t_renderer-${{ matrix.architecture }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: t_renderer-${{ matrix.architecture }}
