name: Releases

on: push
#  push:
#    tags:
#    - '*'

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            architecture: linux-amd64
          - runs-on: macos-latest
            architecture: osx-amd64
          - runs-on: windows-latest
            architecture: windows-amd64
          - runs-on: ubuntu-24.04-arm
            architecture: linux-arm64
          - runs-on: windows-11-arm
            architecture: windows-arm64

    name: Build on ${{ matrix.architecture }}

    steps:
      - name: Setup | Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --verbose --release;

      - name: Upload t_renderer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: t_renderer-${{ matrix.architecture }}
          path: ${{ runner.os == 'Windows' && 'target\\release\\t_renderer.exe' || 'target/release/t_renderer' }}
